// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDoctor(arg1:main.Doctor):Promise<void>;

export function AddPatient(arg1:main.Patient):Promise<void>;

export function BackupDatabase(arg1:boolean):Promise<void>;

export function ClearAllMedicines():Promise<void>;

export function CrawlMedicineData():Promise<void>;

export function CrawlMedicineDataWithPages(arg1:number):Promise<void>;

export function CreateDatabase():Promise<void>;

export function CreateMedicine(arg1:main.Medicine):Promise<main.Medicine>;

export function CreateTemplate(arg1:main.Template):Promise<main.Template>;

export function DeleteDoctor(arg1:number):Promise<void>;

export function DeleteMedicine(arg1:number):Promise<void>;

export function DeletePatient(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function DropDatabase():Promise<void>;

export function ExportPatientsToExcel():Promise<string>;

export function GetAllConfigs():Promise<Record<string, string>>;

export function GetAllDoctors():Promise<Array<main.Doctor>>;

export function GetAllMedicines():Promise<Array<main.Medicine>>;

export function GetAllPatients():Promise<Array<main.Patient>>;

export function GetAllTemplates():Promise<Array<main.Template>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetColumnConfigs():Promise<Array<main.ColumnConfig>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDatabasePath():Promise<string>;

export function GetDoctorByID(arg1:number):Promise<main.Doctor>;

export function GetMedicineByID(arg1:number):Promise<main.Medicine>;

export function GetMedicineCount():Promise<number>;

export function GetMetaInfo():Promise<Record<string, string>>;

export function GetPatientByID(arg1:number):Promise<main.Patient>;

export function GetTemplatesByType(arg1:string):Promise<Array<main.Template>>;

export function InitDefaultColumnConfigs():Promise<void>;

export function MigrateOldDatabase(arg1:string):Promise<void>;

export function SaveColumnConfigs(arg1:Array<main.ColumnConfig>):Promise<void>;

export function SearchDoctors(arg1:string,arg2:string):Promise<Array<main.Doctor>>;

export function SearchMedicines(arg1:string,arg2:string):Promise<Array<main.Medicine>>;

export function SearchPatients(arg1:string,arg2:string):Promise<Array<main.Patient>>;

export function SelectDatabaseFile():Promise<string>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateDoctor(arg1:main.Doctor):Promise<void>;

export function UpdateMedicine(arg1:main.Medicine):Promise<void>;

export function UpdatePatient(arg1:main.Patient):Promise<void>;

export function UpdateTemplate(arg1:main.Template):Promise<void>;
