// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDoctor(arg1) {
  return window['go']['main']['App']['AddDoctor'](arg1);
}

export function AddPatient(arg1) {
  return window['go']['main']['App']['AddPatient'](arg1);
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function CreateDatabase() {
  return window['go']['main']['App']['CreateDatabase']();
}

export function DeleteDoctor(arg1) {
  return window['go']['main']['App']['DeleteDoctor'](arg1);
}

export function DeletePatient(arg1) {
  return window['go']['main']['App']['DeletePatient'](arg1);
}

export function DropDatabase() {
  return window['go']['main']['App']['DropDatabase']();
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAllDoctors() {
  return window['go']['main']['App']['GetAllDoctors']();
}

export function GetAllPatients() {
  return window['go']['main']['App']['GetAllPatients']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetDoctorByID(arg1) {
  return window['go']['main']['App']['GetDoctorByID'](arg1);
}

export function GetMetaInfo() {
  return window['go']['main']['App']['GetMetaInfo']();
}

export function GetPatientByID(arg1) {
  return window['go']['main']['App']['GetPatientByID'](arg1);
}

export function MigrateOldDatabase(arg1) {
  return window['go']['main']['App']['MigrateOldDatabase'](arg1);
}

export function SearchDoctors(arg1, arg2) {
  return window['go']['main']['App']['SearchDoctors'](arg1, arg2);
}

export function SearchPatients(arg1, arg2) {
  return window['go']['main']['App']['SearchPatients'](arg1, arg2);
}

export function SelectDatabaseFile() {
  return window['go']['main']['App']['SelectDatabaseFile']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function UpdateDoctor(arg1) {
  return window['go']['main']['App']['UpdateDoctor'](arg1);
}

export function UpdatePatient(arg1) {
  return window['go']['main']['App']['UpdatePatient'](arg1);
}
