// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDoctor(arg1) {
  return window['go']['main']['App']['AddDoctor'](arg1);
}

export function AddPatient(arg1) {
  return window['go']['main']['App']['AddPatient'](arg1);
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function ClearAllMedicines() {
  return window['go']['main']['App']['ClearAllMedicines']();
}

export function CrawlMedicineData() {
  return window['go']['main']['App']['CrawlMedicineData']();
}

export function CrawlMedicineDataWithPages(arg1) {
  return window['go']['main']['App']['CrawlMedicineDataWithPages'](arg1);
}

export function CreateDatabase() {
  return window['go']['main']['App']['CreateDatabase']();
}

export function CreateMedicine(arg1) {
  return window['go']['main']['App']['CreateMedicine'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function DeleteDoctor(arg1) {
  return window['go']['main']['App']['DeleteDoctor'](arg1);
}

export function DeleteMedicine(arg1) {
  return window['go']['main']['App']['DeleteMedicine'](arg1);
}

export function DeletePatient(arg1) {
  return window['go']['main']['App']['DeletePatient'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DropDatabase() {
  return window['go']['main']['App']['DropDatabase']();
}

export function ExportPatientsToExcel() {
  return window['go']['main']['App']['ExportPatientsToExcel']();
}

export function GetAllConfigs() {
  return window['go']['main']['App']['GetAllConfigs']();
}

export function GetAllDoctors() {
  return window['go']['main']['App']['GetAllDoctors']();
}

export function GetAllMedicines() {
  return window['go']['main']['App']['GetAllMedicines']();
}

export function GetAllPatients() {
  return window['go']['main']['App']['GetAllPatients']();
}

export function GetAllTemplates() {
  return window['go']['main']['App']['GetAllTemplates']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetColumnConfigs() {
  return window['go']['main']['App']['GetColumnConfigs']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetDoctorByID(arg1) {
  return window['go']['main']['App']['GetDoctorByID'](arg1);
}

export function GetMedicineByID(arg1) {
  return window['go']['main']['App']['GetMedicineByID'](arg1);
}

export function GetMedicineCount() {
  return window['go']['main']['App']['GetMedicineCount']();
}

export function GetMetaInfo() {
  return window['go']['main']['App']['GetMetaInfo']();
}

export function GetPatientByID(arg1) {
  return window['go']['main']['App']['GetPatientByID'](arg1);
}

export function GetTemplatesByType(arg1) {
  return window['go']['main']['App']['GetTemplatesByType'](arg1);
}

export function InitDefaultColumnConfigs() {
  return window['go']['main']['App']['InitDefaultColumnConfigs']();
}

export function MigrateOldDatabase(arg1) {
  return window['go']['main']['App']['MigrateOldDatabase'](arg1);
}

export function OpenDatabaseLocation() {
  return window['go']['main']['App']['OpenDatabaseLocation']();
}

export function SaveColumnConfigs(arg1) {
  return window['go']['main']['App']['SaveColumnConfigs'](arg1);
}

export function SearchDoctors(arg1, arg2) {
  return window['go']['main']['App']['SearchDoctors'](arg1, arg2);
}

export function SearchMedicines(arg1, arg2) {
  return window['go']['main']['App']['SearchMedicines'](arg1, arg2);
}

export function SearchPatients(arg1, arg2) {
  return window['go']['main']['App']['SearchPatients'](arg1, arg2);
}

export function SelectDatabaseFile() {
  return window['go']['main']['App']['SelectDatabaseFile']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function UpdateDoctor(arg1) {
  return window['go']['main']['App']['UpdateDoctor'](arg1);
}

export function UpdateMedicine(arg1) {
  return window['go']['main']['App']['UpdateMedicine'](arg1);
}

export function UpdatePatient(arg1) {
  return window['go']['main']['App']['UpdatePatient'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['main']['App']['UpdateTemplate'](arg1);
}
