// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDoctor(arg1:main.Doctor):Promise<void>;

export function AddPatient(arg1:main.Pig):Promise<void>;

export function BackupDatabase(arg1:boolean):Promise<void>;

export function CreateDatabase():Promise<void>;

export function DeleteDoctor(arg1:number):Promise<void>;

export function DeletePatient(arg1:number):Promise<void>;

export function DropDatabase():Promise<void>;

export function GetAllConfigs():Promise<Record<string, string>>;

export function GetAllDoctors():Promise<Array<main.Doctor>>;

export function GetAllPatients():Promise<Array<main.Pig>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDatabasePath():Promise<string>;

export function GetDoctorByID(arg1:number):Promise<main.Doctor>;

export function GetMetaInfo():Promise<Record<string, string>>;

export function GetPatientByID(arg1:number):Promise<main.Pig>;

export function MigrateOldDatabase(arg1:string):Promise<void>;

export function SearchDoctors(arg1:string,arg2:string):Promise<Array<main.Doctor>>;

export function SearchPatients(arg1:string,arg2:string):Promise<Array<main.Pig>>;

export function SelectDatabaseFile():Promise<string>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateDoctor(arg1:main.Doctor):Promise<void>;

export function UpdatePatient(arg1:main.Pig):Promise<void>;
